### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by dmattsson** [tuya/tuya-home-ios-sdk-sample-swift#11]
Hi

I followed the README guide, but cannot build the project.

```
Undefined symbol: _OBJC_CLASS_$_SGScanCode
Undefined symbol: _OBJC_CLASS_$_SGScanView
Undefined symbol: _OBJC_CLASS_$_SGScanViewConfigure
Undefined symbol: _OBJC_CLASS_$_SVProgressHUD
Undefined symbol: _SVProgressHUDDidDisappearNotification
Undefined symbol: _SVProgressHUDStatusUserInfoKey
```

Any ideas?

![image](https://user-images.githubusercontent.com/8665566/220594766-49eea50a-43ca-4b59-9f20-9baa02216790.png)

**Comment by taojingGino** [comment]
its seems like you use M1 cpu Mac，try the first and fifth points @dmattsson 

https://developer.tuya.com/cn/docs/app-development/faq?id=Ka5vc94omshzp#title-20-5.%20M1%20%E8%8A%AF%E7%89%87%E7%9A%84%E7%94%B5%E8%84%91%E7%BC%96%E8%AF%91%20iOS%20%E4%B8%BA%E4%BB%80%E4%B9%88%E6%8A%A5%E9%94%99%20Undefined%20symbols%20for%20architecture%20arm64%EF%BC%9F

**Comment by dmattsson** [comment]
Thank you @taojingGino! I managed to solve it by running XCode in Rosetta mode instead.
