### ISSUE TITLE
build failed Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by rome753** [tuya/tuya-home-ios-sdk-sample-swift#12]
On m1 mac. I have checked all closed issues and [faq](https://developer.tuya.com/cn/docs/app-development/faq?id=Ka5vc94omshzp#title-20-5.%20M1%20%E8%8A%AF%E7%89%87%E7%9A%84%E7%94%B5%E8%84%91%E7%BC%96%E8%AF%91%20iOS%20%E4%B8%BA%E4%BB%80%E4%B9%88%E6%8A%A5%E9%94%99%20Undefined%20symbols%20for%20architecture%20arm64%EF%BC%9F) but not solved.

`Undefined symbols for architecture arm64:
  "_read_keys_from_content", referenced from:
      +[TYActivatorUtils getSecretKey] in ThingSmartPairingCoreKit(TYActivatorUtils.o)
      -[ThingSmartCore ThingCoreOrangesSmallTomato] in ThingSmartUtil(ThingSmartCore.o)
  "_read_keys_from_file", referenced from:
      -[ThingSmartCore ThingCoreStrawberriesWalnuts:ThingCoreStrawberriesPeach:] in ThingSmartUtil(ThingSmartCore.o)
  "_thingctypt_CString", referenced from:
      -[ThingSmartCore ThingCoreOrangesSmallTomato] in ThingSmartUtil(ThingSmartCore.o)
  "_thingctypt_OCString", referenced from:
      +[ThingBLELocalEncryption saveLocalEncryptionUserDefalutDouble:key:] in ThingSmartBLEKit(ThingBLELocalEncryption.o)
      +[ThingBLELocalEncryption localEncryptionUserDefalutToData:] in ThingSmartBLEKit(ThingBLELocalEncryption.o)
      +[ThingBLELocalEncryption saveLocalEncryptionData:filePath:] in ThingSmartBLEKit(ThingBLELocalEncryption.o)
      +[ThingBLELocalEncryption getLocalEncryptionUserDefalutDouble:] in ThingSmartBLEKit(ThingBLELocalEncryption.o)
      +[ThingBLELocalEncryption saveLocalEncryptionUserDefalutData:key:] in ThingSmartBLEKit(ThingBLELocalEncryption.o)
      +[ThingBLELocalEncryption getLocalEncryptionUserDefalutData:] in ThingSmartBLEKit(ThingBLELocalEncryption.o)
      +[ThingBLELocalEncryption saveLocalEncryptionDocumentData:filePath:] in ThingSmartBLEKit(ThingBLELocalEncryption.o)
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by taojingGino** [comment]
> On m1 mac. I have checked all closed issues and [faq](https://developer.tuya.com/cn/docs/app-development/faq?id=Ka5vc94omshzp#title-20-5.%20M1%20%E8%8A%AF%E7%89%87%E7%9A%84%E7%94%B5%E8%84%91%E7%BC%96%E8%AF%91%20iOS%20%E4%B8%BA%E4%BB%80%E4%B9%88%E6%8A%A5%E9%94%99%20Undefined%20symbols%20for%20architecture%20arm64%EF%BC%9F) but not solved.
> 
> `Undefined symbols for architecture arm64: "_read_keys_from_content", referenced from: +[TYActivatorUtils getSecretKey] in ThingSmartPairingCoreKit(TYActivatorUtils.o) -[ThingSmartCore ThingCoreOrangesSmallTomato] in ThingSmartUtil(ThingSmartCore.o) "_read_keys_from_file", referenced from: -[ThingSmartCore ThingCoreStrawberriesWalnuts:ThingCoreStrawberriesPeach:] in ThingSmartUtil(ThingSmartCore.o) "_thingctypt_CString", referenced from: -[ThingSmartCore ThingCoreOrangesSmallTomato] in ThingSmartUtil(ThingSmartCore.o) "_thingctypt_OCString", referenced from: +[ThingBLELocalEncryption saveLocalEncryptionUserDefalutDouble:key:] in ThingSmartBLEKit(ThingBLELocalEncryption.o) +[ThingBLELocalEncryption localEncryptionUserDefalutToData:] in ThingSmartBLEKit(ThingBLELocalEncryption.o) +[ThingBLELocalEncryption saveLocalEncryptionData:filePath:] in ThingSmartBLEKit(ThingBLELocalEncryption.o) +[ThingBLELocalEncryption getLocalEncryptionUserDefalutDouble:] in ThingSmartBLEKit(ThingBLELocalEncryption.o) +[ThingBLELocalEncryption saveLocalEncryptionUserDefalutData:key:] in ThingSmartBLEKit(ThingBLELocalEncryption.o) +[ThingBLELocalEncryption getLocalEncryptionUserDefalutData:] in ThingSmartBLEKit(ThingBLELocalEncryption.o) +[ThingBLELocalEncryption saveLocalEncryptionDocumentData:filePath:] in ThingSmartBLEKit(ThingBLELocalEncryption.o) ... ld: symbol(s) not found for architecture arm64 clang: error: linker command failed with exit code 1 (use -v to see invocation)`

you need go to https://iot.tuya.com/, and creat an SDK App, and download "ThingSmartCryption", than add into your Podfile.
you can see it in this docment
https://developer.tuya.com/cn/docs/app-development/integrate-sdk?id=Ka5d52ewngdoi#title-2-%E6%9E%84%E5%BB%BA%E5%92%8C%E4%B8%8B%E8%BD%BD%20SDK

**Comment by rome753** [comment]
Thanks
