### ISSUE TITLE
Getting error on running Pod install

### ISSUE THREAD

**Issue by atuljha3334** [tuya/tuya-home-ios-sdk-sample-swift#18]
I'm getting following error on running pod install:

-> No podspec found for `ThingSmartCryption` in `./ios_core_sdk`

I tried changing :path => to :git => but that gave me this error:

-> Pre-downloading: `ThingSmartCryption` from `./ios_core_sdk`

[!] Error installing ThingSmartCryption
[!] Failed to download 'ThingSmartCryption': [!] /usr/bin/git clone ./ios_core_sdk /var/folders/z9/6kjl25c55pxg3n2_r5rn2zsw0000gn/T/d20240110-7032-519dhx --template= --single-branch --depth 1

fatal: repository './ios_core_sdk' does not exist

**Comment by miyazaki2048** [comment]
https://developer.tuya.com/en/docs/app-development/integrate-sdk?id=Ka5d52ewngdoi#title-2-Build%20and%20download%20the%20SDK
