### ISSUE TITLE
Persistent 2FA Authentication Error with Tuya SDK on iOS Simulator

### ISSUE THREAD

**Issue by anatoleplanteur** [tuya/tuya-home-ios-sdk-sample-swift#19]
Hello Tuya Developer Team,

I have been working on integrating the Tuya SDK for a 2FA login feature within an iOS application. Although the cloud project is correctly connected and all API keys and credentials have been meticulously verified, there is a persistent error that surfaces when attempting to send the 2FA code using the iOS Simulator via Xcode.

The error is as follows:
`sendVerifyCode failure: Error Domain=com.thing.www Code=1501 "Permission Verification Failed" UserInfo={NSLocalizedDescription=Permission Verification Failed, NSLocalizedFailureReason=SING_VALIDATE_FAILED}`

After reaching out to thesupport team, I was advised to refer to the documentation. However, the documentation did not address this specific scenario. I have already configured 'Allow Arbitrary Loads' in the App Transport Security settings to ensure there are no ATS issues affecting the connection.

I am reaching out here in hopes of receiving more detailed support to overcome this roadblock. Any suggestions or guidance you could offer would be greatly appreciated.

Screen : [http://tinyurl.com/yrldhnnl](url)

**Comment by anatoleplanteur** [comment]
![Uploading Screenshot 2024-01-10 at 18.16.53.png…]()

**Comment by taojingGino** [comment]
@anatoleplanteur this error means your bundleid, appkey, secretKey and ThingSmartCryption not match. 
Make sure that BundleId, AppKey, and AppSecret are consistent with those used on the [Tuya IoT Development Platform](https://iot.tuya.com/). Any mismatch will cause the authentication to be failed. For more information, see [Preparation](https://developer.tuya.com/en/docs/app-development/preparation/preparation?id=Ka69nt983bhh5).

pls check this doc
https://developer.tuya.com/en/docs/app-development/integrate-sdk?id=Ka5d52ewngdoi#title-3-Use%20CocoaPods%20for%20fast%20integration
