### ISSUE TITLE
Crash after calling ThingSmartRoomBiz.sharedInstance().getRoomList

### ISSUE THREAD

**Issue by dodyac** [tuya/tuya-home-ios-sdk-sample-swift#20]
How to reproduce
 If I go to room list screen, after the room list loaded, I am getting a crash
<img width="1437" alt="Screenshot 2024-02-29 at 10 22 20" src="https://github.com/tuya/tuya-home-ios-sdk-sample-swift/assets/37199748/09648df7-0915-4230-9461-b3db3818ac18">

**Comment by rishatl** [comment]
Hey, I'll take it upon myself, make me assignees, pls

**Comment by taojingGino** [comment]
@dodyac 
We did not reproduce your issue by running the demo locally, so we suspect that the crash was caused by a data issue. We suggest that you break a point near the getRoomList method and investigate step by step whether the data meets your expectations

**Comment by dodyac** [comment]
Im using simulator and getting crash, but when im using real device its not getting crash

**Comment by taojingGino** [comment]
@dodyac 
yeah，you can use real device first，we are fixing the problem about simulator
