### ISSUE TITLE
Infinity errors, when try to launch

### ISSUE THREAD

**Issue by b0r1ngx** [tuya/tuya-home-ios-sdk-sample-swift#21]
I made all by guides at README.md and at https://developer.tuya.com/en/docs/app-development/integrate-sdk?id=Ka5d52ewngdoi

When i try to build / run project, get errors like this:
<img width="1411" alt="image" src="https://github.com/tuya/tuya-home-ios-sdk-sample-swift/assets/55315908/b76e138a-35af-4bc8-b525-e9427000a0ab">

Device: Apple Macbook M2 Pro
macOS: 14.3.1 (23D60)
XCode Version 15.2 (15C500b)

Our company wants to try your solution in smart home and buy if we get satisfied.
But our developers are getting errors by your guides/samples and can't explore the things.

Help us please!

Best regards,
Kirill I. A.

**Comment by taojingGino** [comment]
Could you please send me your Podfile and Podfile.lock files?

**Comment by b0r1ngx** [comment]
> Could you please send me your Podfile and Podfile.lock files?

Yes, sure, Podfile is just default from project, i tried to comment a line, that excludes arm64, but thing that doesn't real make matter for me (because im in real doesn't undertsand target and things of it)
(I'm added .txt and the end of the file just to attach it here)
[Podfile.txt](https://github.com/tuya/tuya-home-ios-sdk-sample-swift/files/14507220/Podfile.txt)
[Podfile.lock.txt](https://github.com/tuya/tuya-home-ios-sdk-sample-swift/files/14507222/Podfile.lock.txt)

We tried macbook on intel, and this projects builded and runs good!


Also, one good thing, what I can say, yesterday we successfully runs Tuya SDK at clear project, and trying go further (connect and auth smart things at home)
---
Half of the day we have problems, and at end of the day (close to night) we successfully runs it!

**Comment by taojingGino** [comment]
This is really great. If you have any questions, you can provide feedback again

**Comment by b0r1ngx** [comment]
Why did you close an issue?

What pod-files gives you, you doesn't give any response on this info?
**We still can't run this sample** on M-chip apple laptop mac's.

Also, i suppose that you help at new issue (with a new problem).
