### ISSUE TITLE
No such module 'ThingSmartAppleDeviceKit'

### ISSUE THREAD

**Issue by hung-le-fs** [tuya/tuya-home-ios-sdk-sample-swift#24]
I attempted to integrate my app with ThingSmartAppleDeviceKit using the pod:

pod 'ThingSmartAppleDeviceKit', '~> 5.1.0'

However, I encountered the error message: 'No such module 'ThingSmartAppleDeviceKit'.'

The 'pod install' command executed successfully, and I confirmed that ThingSmartAppleDeviceKit.xcframework exists.

**Comment by taojingGino** [comment]
@hung-le-fs 
did you add this source?
source 'https://github.com/tuya/tuya-pod-specs.git'

and here is the version of ThingSmartAppleDeviceKit
https://github.com/tuya/tuya-pod-specs/tree/main/ThingSmartAppleDeviceKit

**Comment by hung-le-fs** [comment]
Hi @taojingGino 
Thanks for your support.
Here is my Podfile:
> source 'https://github.com/CocoaPods/Specs'
> source 'https://github.com/tuya/TuyaPublicSpecs.git'
> source 'https://github.com/tuya/tuya-pod-specs.git'
> ## platform :ios, '14.0'
>
> target 'Test Tuya' do
>   use_frameworks!
> pod 'ThingSmartCryption', :path => './Frameworks/ios_core_sdk'
> pod 'ThingSmartHomeKit',  '~>  5.8.0'
> pod 'ThingSmartMatterKit',  '~>  5.4.0'
> pod 'ThingSmartAppleDeviceKit',  '~>  5.1.0'
>
> end


ThingSmartAppleDeviceKit.xcframework is existed in Pod folder(pod project) but I can not import to project.
![Screenshot 2024-04-23 at 9 52 43 AM](https://github.com/tuya/tuya-home-ios-sdk-sample-swift/assets/138755609/94b0b860-06c0-4e2a-87bc-56ecc7e87323)

![Screenshot 2024-04-22 at 11 40 03 AM](https://github.com/tuya/tuya-home-ios-sdk-sample-swift/assets/138755609/aaccfb9c-72fe-459b-abd3-bf88d11b512d)

**Comment by taojingGino** [comment]
Hi @hung-le-fs 
use this version can fix this issue
pod 'ThingSmartAppleDeviceKit', '~> 5.1.1'

**Comment by hung-le-fs** [comment]
So weird, still this error.
