### ISSUE TITLE
Crashed when run the code

### ISSUE THREAD

**Issue by NandParikh** [tuya/tuya-home-ios-sdk-sample-swift#25]
I have used this demo and followed the steps from integration document: https://developer.tuya.com/cn/docs/app-development/integrate-sdk?id=Ka5d52ewngdoi

I added the build folder and ThingSmartCryption.podspec file in the same place where the pod file is placed and then tried to run the project but I am getting crash.

Here is the logs which I am getting in the console. It may help to troubleshoot the problem.

2024-07-12 15:08:49 [ERROR] <ThingSmartNetworkKit> Init dns cache
2024-07-12 15:08:49 [OTHER] <ThingSmartNetworkKit> load t_cdc.tcfg finish: (null) 
 error: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0., NSJSONSerializationErrorIndex=0}
2024-07-12 15:08:49 [OTHER] <ThingSmartNetworkKit> t_cdc.tcfg load failed.(format error)

**Comment by manhninh** [comment]
Hi @NandParikh , Have you solved this problem yet? Can you share information with me?

**Comment by manhninh** [comment]
@NandParikh , Please config Bundle Identifier same iOS Bundle ID on Tuya Developer Platform

**Comment by taojingGino** [comment]
@NandParikh 
year config Bundle Identifier same iOS Bundle ID on Tuya Developer Platform
have you solved this problem yet?
