### ISSUE TITLE
Permission verification error

### ISSUE THREAD

**Issue by AndreyNovikov2909** [tuya/tuya-home-ios-sdk-sample-swift#6]
Hello I have a problem with obtaining a verification code during authorization, I cloned your project, indicated the correct appKey and privateKey and also placed a secret picture on the same level with info.plist but I always get an error with sdk, I live in Kazakhstan my coutry code equal to 7. This is what I get in the response -

2021-07-03 03:57:57.449468+0600 TuyaAppSDKSample-iOS-Swift[80191:5380126] [TYRequest] request: domain = https://a1.tuyaeu.com, url = https://52.28.3.175/api.json, api = tuya.m.user.username.code.get, commonParams = {
  "time" : "1625263077",
  "lang" : "en",
  "deviceId" : "36D51D54-41C0-4364-B705-C40B6492F51E",
  "et" : "0.0.2",
  "osSystem" : "13.0",
  "bundleId" : "ru.andrenovikov",
  "lon" : 0,
  "channel" : "sdk",
  "appVersion" : "1.0",
  "ttid" : "appstore_d",
  "os" : "IOS",
  "v" : "3.0",
  "sign" : "f1975eccf9a002f5de0ec02ff836fd67639cbe89f798886a93f037ec34b48469",
  "platform" : "Simulator",
  "requestId" : "78201902-CD66-4225-BD3F-621CE2EEC9F3",
  "sdkVersion" : "3.26.5",
  "timeZoneId" : "Asia\/Almaty",
  "lat" : 0,
  "clientId" : "7cq3unfcy8djd7hmavwv",
  "a" : "tuya.m.user.username.code.get"
}, businessParams = {
  "countryCode" : "7",
  "username" : "novikovandrey2000@gmail.com",
  "codeType" : 1
}
2021-07-03 03:57:57.576174+0600 TuyaAppSDKSample-iOS-Swift[80191:5384497] connect time : {"at":"126","ct":"0","tt":"0","rc":0,"mc":1,"dt":"0"}
2021-07-03 03:57:57.576607+0600 TuyaAppSDKSample-iOS-Swift[80191:5385289] [TYRequest] response: api = tuya.m.user.username.code.get, data = {
  "success" : false,
  "errorCode" : "SING_VALIDATE_FALED",
  "status" : "error",
  "errorMsg" : "Permission Verification Failed",
  "t" : 1625263077499
}
2021-07-03 03:57:57.579048+0600 TuyaAppSDKSample-iOS-Swift[80191:5385289] SING_VALIDATE_FALED: appKey = 7cq3************avwv, appSecret = dsp4************************9qyh, bundleId = (null), imageMd5 = 82f4b56fba131899d5c24c10ac1606e4
2021-07-03 03:59:59.592581+0600 TuyaAppSDKSample-iOS-Swift[80191:5380126] Can't find keyplane that supports type 4 for keyboard iPhone-PortraitChoco-NumberPad; using 25671_PortraitChoco_iPhone-Simple-Pad_Default

**Comment by xiaoxuan-Tuya** [comment]
Hi , AndreyNovikov 

Thanks for your feedback ! It seems that you want to request verification code for register with your  phone number ,right ? If so , make sure that you had added the area in the allowlist (see the [tutorial](https://developer.tuya.com/en/docs/app-development/tutorial-for-ios-account?id=Kalawg5deam3k#title-4-Query%20areas%20for%20the%20verification%20code%20service) ) .   For the privacy and security of user information, we have optimized the mobile phone number registration mechanism. If you want to use the mobile phone number registration service, you can contact the relevant docking business .

**Comment by taojingGino** [comment]
> Hello I have a problem with obtaining a verification code during authorization, I cloned your project, indicated the correct appKey and privateKey and also placed a secret picture on the same level with info.plist but I always get an error with sdk, I live in Kazakhstan my coutry code equal to 7. This is what I get in the response -
> 
> 2021-07-03 03:57:57.449468+0600 TuyaAppSDKSample-iOS-Swift[80191:5380126] [TYRequest] request: domain = https://a1.tuyaeu.com, url = https://52.28.3.175/api.json, api = tuya.m.user.username.code.get, commonParams = {
> "time" : "1625263077",
> "lang" : "en",
> "deviceId" : "36D51D54-41C0-4364-B705-C40B6492F51E",
> "et" : "0.0.2",
> "osSystem" : "13.0",
> "bundleId" : "ru.andrenovikov",
> "lon" : 0,
> "channel" : "sdk",
> "appVersion" : "1.0",
> "ttid" : "appstore_d",
> "os" : "IOS",
> "v" : "3.0",
> "sign" : "f1975eccf9a002f5de0ec02ff836fd67639cbe89f798886a93f037ec34b48469",
> "platform" : "Simulator",
> "requestId" : "78201902-CD66-4225-BD3F-621CE2EEC9F3",
> "sdkVersion" : "3.26.5",
> "timeZoneId" : "Asia/Almaty",
> "lat" : 0,
> "clientId" : "7cq3unfcy8djd7hmavwv",
> "a" : "tuya.m.user.username.code.get"
> }, businessParams = {
> "countryCode" : "7",
> "username" : "[novikovandrey2000@gmail.com](mailto:novikovandrey2000@gmail.com)",
> "codeType" : 1
> }
> 2021-07-03 03:57:57.576174+0600 TuyaAppSDKSample-iOS-Swift[80191:5384497] connect time : {"at":"126","ct":"0","tt":"0","rc":0,"mc":1,"dt":"0"}
> 2021-07-03 03:57:57.576607+0600 TuyaAppSDKSample-iOS-Swift[80191:5385289] [TYRequest] response: api = tuya.m.user.username.code.get, data = {
> "success" : false,
> "errorCode" : "SING_VALIDATE_FALED",
> "status" : "error",
> "errorMsg" : "Permission Verification Failed",
> "t" : 1625263077499
> }
> 2021-07-03 03:57:57.579048+0600 TuyaAppSDKSample-iOS-Swift[80191:5385289] SING_VALIDATE_FALED: appKey = 7cq3************avwv, appSecret = dsp4************************9qyh, bundleId = (null), imageMd5 = 82f4b56fba131899d5c24c10ac1606e4
> 2021-07-03 03:59:59.592581+0600 TuyaAppSDKSample-iOS-Swift[80191:5380126] Can't find keyplane that supports type 4 for keyboard iPhone-PortraitChoco-NumberPad; using 25671_PortraitChoco_iPhone-Simple-Pad_Default

pls check your bundleId is correct

**Comment by l2feed** [comment]
> > Hello I have a problem with obtaining a verification code during authorization, I cloned your project, indicated the correct appKey and privateKey and also placed a secret picture on the same level with info.plist but I always get an error with sdk, I live in Kazakhstan my coutry code equal to 7. This is what I get in the response -
> > 2021-07-03 03:57:57.449468+0600 TuyaAppSDKSample-iOS-Swift[80191:5380126] [TYRequest] request: domain = https://a1.tuyaeu.com, url = https://52.28.3.175/api.json, api = tuya.m.user.username.code.get, commonParams = {
> > "time" : "1625263077",
> > "lang" : "en",
> > "deviceId" : "36D51D54-41C0-4364-B705-C40B6492F51E",
> > "et" : "0.0.2",
> > "osSystem" : "13.0",
> > "bundleId" : "ru.andrenovikov",
> > "lon" : 0,
> > "channel" : "sdk",
> > "appVersion" : "1.0",
> > "ttid" : "appstore_d",
> > "os" : "IOS",
> > "v" : "3.0",
> > "sign" : "f1975eccf9a002f5de0ec02ff836fd67639cbe89f798886a93f037ec34b48469",
> > "platform" : "Simulator",
> > "requestId" : "78201902-CD66-4225-BD3F-621CE2EEC9F3",
> > "sdkVersion" : "3.26.5",
> > "timeZoneId" : "Asia/Almaty",
> > "lat" : 0,
> > "clientId" : "7cq3unfcy8djd7hmavwv",
> > "a" : "tuya.m.user.username.code.get"
> > }, businessParams = {
> > "countryCode" : "7",
> > "username" : "[novikovandrey2000@gmail.com](mailto:novikovandrey2000@gmail.com)",
> > "codeType" : 1
> > }
> > 2021-07-03 03:57:57.576174+0600 TuyaAppSDKSample-iOS-Swift[80191:5384497] connect time : {"at":"126","ct":"0","tt":"0","rc":0,"mc":1,"dt":"0"}
> > 2021-07-03 03:57:57.576607+0600 TuyaAppSDKSample-iOS-Swift[80191:5385289] [TYRequest] response: api = tuya.m.user.username.code.get, data = {
> > "success" : false,
> > "errorCode" : "SING_VALIDATE_FALED",
> > "status" : "error",
> > "errorMsg" : "Permission Verification Failed",
> > "t" : 1625263077499
> > }
> > 2021-07-03 03:57:57.579048+0600 TuyaAppSDKSample-iOS-Swift[80191:5385289] SING_VALIDATE_FALED: appKey = 7cq3************avwv, appSecret = dsp4************************9qyh, bundleId = (null), imageMd5 = 82f4b56fba131899d5c24c10ac1606e4
> > 2021-07-03 03:59:59.592581+0600 TuyaAppSDKSample-iOS-Swift[80191:5380126] Can't find keyplane that supports type 4 for keyboard iPhone-PortraitChoco-NumberPad; using 25671_PortraitChoco_iPhone-Simple-Pad_Default
> 
> pls check your bundleId is correct

I check my bundleid, and also created a new project with my bunble, but I still get an error with bundleid when prompted for a verification code, can you tell me how sdk should take the bundleid from my project

error: - SING_VALIDATE_FALED: appKey = 7cq3 ************ avwv, appSecret = dsp4 ********************************* 9qyh , bundleId = (null), imageMd5 = 82f4b56fba131899d5c24c10ac1606e4
