### ISSUE TITLE
i have a fatal error when i run app

### ISSUE THREAD

**Issue by Ramiz69** [tuya/tuya-home-ios-sdk-sample-swift#8]
Terminating app due to uncaught exception 'TuyaSmartSDKException', reason: 'Security image not found. Please refer to: https://tuyainc.github.io/tuyasmart_home_ios_sdk_doc/en/resource/Preparation.html'

Page not found

**Comment by huangdaxiaEX** [comment]
Build an app based on iOS App SDK on the Tuya IoT Platform, and get the values of `AppKey` and `AppSecret` and `the security image` of the App SDK, please see:
https://developer.tuya.com/en/docs/app-development/preparation?id=Ka69nt983bhh5
https://developer.tuya.com/en/docs/app-development/integrate-sdk?id=Ka5d52ewngdoi#title-9-Prepare%20the%20demo
